<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_TemperatureMonitor" Id="{f2f27cc4-d6ae-4c5d-804a-03189889dd36}" SpecialFunc="None">
    <Declaration><![CDATA[// Monitors temperature sensors
FUNCTION_BLOCK FB_TemperatureMonitor
VAR_INPUT
    nTempMonRaw : INT; // Raw signal from the ADC
END_VAR
VAR_OUTPUT
    {attribute 'pytmc' := '
        pv: TEMP
        io: i
        field: EGU C
        field: LOPR 0.0
        field: HOPR 1000
        field: LSV MINOR
    '}
    fTemperature : LREAL; // Temperature reading in celsius
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Scale the signed int value from the input to an output reading in celsius
fTemperature := INT_TO_LREAL(nTempMonRaw) / 10;	]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>